### ISSUE TITLE
Add router fragments - anchor links

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-website#100]
Since the new Router of Angular 2 now supports anchor links, it would be great if we start to implement anchor links in a proper way if we are currently linking to sections of a route.

You can see how to implement this by going to the following:
- http://stackoverflow.com/questions/36101756/angular2-routing-with-hashtag-to-page-anchor
- https://angular.io/docs/ts/latest/guide/router.html#!#fragment

**Comment by jgf20** [comment]
We change our website from angular to a static site generator.
