### ISSUE TITLE
Restructure two-column section in the front page

### ISSUE THREAD

**Issue by MiguelAraCo** [CarbonLDP/carbonldp-website#111]
![home___carbon_ldp_](https://cloud.githubusercontent.com/assets/8313806/20188708/80c32644-a73f-11e6-98ec-494da11a4e01.jpg)
This section needs several changes:
- Center both vertically and horizontally based on the container. Like in this [codepen](http://codepen.io/MiguelAraCo/pen/JbGKRy)
- Remove quotes from the second column
- Replace header tags for normal paragraph tags styled with css

**Comment by jgf20** [comment]
This issue belongs to our old website project and was fixed.
