### ISSUE TITLE
JavaScript SDK API Reference link is broken.

### ISSUE THREAD

**Issue by mhernandeza** [CarbonLDP/carbonldp-website#125]
The JavaScript SDK API Reference link located in the Community & Support section of the website is broken. I was able to access the documentation through a link ( http://carbonldp.github.io/carbonldp-js-sdk/ ) Miguel posted in the carbonldp-js-sdk Gitter room. 

Also, I would suggest placing the link to that documentation on the Documentation > Javascript SDK section of the website where it is more intuitive for people to expect it.

**Comment by jgf20** [comment]
Fixed in https://github.com/CarbonLDP/carbonldp-website/pull/129
