### ISSUE TITLE
Breadcrumb link of Javascript SDK not working

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-website#127]
When clicking the `documentation` link of the breadcrumb of the SDK documentation landing page (https://carbonldp.com/documentation/javascript-sdk), the link is not working, it should redirect to the documentation homepage but it's doing nothing.

**Comment by jgf20** [comment]
Fixed in https://github.com/CarbonLDP/carbonldp-website/pull/129
