### ISSUE TITLE
Do we still recommend JSPM as stated in Website documentation

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#154]
Since we've moved to WebPack, do you think we should still keep documentation representing a recommendation for JSPM?

![do-we-still-recommend-jspm](https://cloud.githubusercontent.com/assets/7317733/25055216/14dc77a2-2127-11e7-872f-dad626375f26.jpg)

**Comment by MiguelAraCo** [comment]
The new version doesn't have this recommendation anymore
