### ISSUE TITLE
Update config.yaml example and add a cross-link in v1.0.x (alpha) Getting Started

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#176]
On the following page...

[https://carbonldp.com/documentation/v1.0.x/quick-start-guide/](https://carbonldp.com/documentation/v1.0.x/quick-start-guide/)

... the config.yaml example is not up to date (according to Miguel). For example, right now it says:

```
#repository:
#  # Type of repository to use (can be 'local' or 'remote')
```

and it should say...

`# Type of repository to use (can be 'local', 'remote' or 'stardog')`

Also, we need to provide a cross-link in this area. Within, above or below the config.yaml; somewhere close by. One option is to provide a link in a comment within the config.yaml:

```
# To configure another repository such as Stardog or Graph DB here, refer to:
# https://carbonldp.com/documentation/v1.0.x/platform/enterprise-class-repositories/
```
If we do not provide that note within the yaml, it should be close by in the documentation; some reference to this other page.

**Comment by MiguelAraCo** [comment]
Fixed
