### ISSUE TITLE
Update Getting Started around modules to reflect potential need for node types

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#185]
In the Getting Started guide here:

https://carbonldp.com/documentation/v1.0.x/javascript-sdk/getting-started/

Installing the SDK > npm

The following may not be sufficient alone:

`npm install carbonldp --save`

On my machine, I needed also to do:

`npm install carbonldp @types/node --save`

So, the documentation might need to say the following instead:

`npm install carbonldp @types/node --save`

See issue: https://github.com/CarbonLDP/carbonldp-js-sdk/issues/193

**Comment by MiguelAraCo** [comment]
You only need `@types/node` if you are using typescript so it is not a required dependency (in that case `typescript` would also be one).

**Comment by MiguelAraCo** [comment]
Version `1.0.0-alpha.11` adds `@types/node` as a dependency so this is no longer an issue
