### ISSUE TITLE
Consider adding a "How to translate an Object Oriented System into its Linked Data version"

### ISSUE THREAD

**Issue by alex-arriaga** [CarbonLDP/carbonldp-website#193]
One of the things we usually ask ourselves is how to translate our Object Oriented programs into Linked Data stuff, (for example how to name the properties for a given schema, what is the equivalent to a relationship between OO classes, etc.).

Let's imagine I want to create a Blog in Carbon, I could have two data models with these kind of relations:

Post hasMany Comment
Comment belongsTo Post

In an Object Oriented approach this relations could be modeled as follows:

```
class Post {
	comments: List<Comment>;
}

Comment {
	post: Post
}
```

Translated into a "Linked Data" mindset:

Post should have an schema with properties
Comment should have an schema with properties
That's very clear...

However, when talking about how to represent my "comments" list, things change... should that be a container? what is container anyways? should that be an access point? 

It would be awesome to have documentation about "How to translate an Object Oriented System into its Linked Data version".

**Comment by MiguelAraCo** [comment]
We consider this to be part of a potential "Best practices" guide, which we aren't comfortable publishing right now as the usage of Carbon is limited. For now the CarbonLDP team will only provide the tool and its usage is up to the users.
