### ISSUE TITLE
Typo error on SDK documentation.

### ISSUE THREAD

**Issue by AlexSerrano22** [CarbonLDP/carbonldp-website#194]
on the documentation of creating an access point on the tab "JavaScript ES2015", you have this lines:
```
        return project.refresh<Project>();
        return person1.refresh<Person>();
```
but the classes are on "typescript" only

https://carbonldp.com/documentation/v1.0.x/javascript-sdk/access-points/

**Comment by alvaro9210** [comment]
Closing in favor of #208

**Comment by MiguelAraCo** [comment]
The issue has been fixed
