### ISSUE TITLE
Include argument in Examples of "Creating a carbon Object" section in v1.0.x alpha documentation

### ISSUE THREAD

**Issue by andynice** [CarbonLDP/carbonldp-website#199]
`let carbon:Carbon = new Carbon( "my-carbon-instance.com:8080" );`

It could be helpful if it includes the second argument, as in the last example

`let carbon:Carbon = new Carbon( "localhost:8083", false ); // Turning off HTTPS (only needed if your server isn't using it)`

**Comment by alvaro9210** [comment]
Closing because the new proposed Carbon constructor signatures work the way the documentation indicates. Opened #209 to reflect the small changes that are still to be made.
