### ISSUE TITLE
Consider explaining if there is any impact on performance when using fragments vs named fragments

### ISSUE THREAD

**Issue by alex-arriaga** [CarbonLDP/carbonldp-website#214]
One of the questions that came to my mind is, if I choose the named fragments, or the regular fragments, would that affect the performance of my app? which other advantages do I get with named fragments, a part from being able to reference the named fragments from outside the document?

<img width="1416" alt="screen shot 2018-01-31 at 12 07 30 pm" src="https://user-images.githubusercontent.com/1860518/35639308-711679d0-067f-11e8-920d-502720afd44b.png">

**Comment by MiguelAraCo** [comment]
There is no known performance impact. If the documentation doesn't state that there is, you shouldn't be worried about it. If you are still worried, you can always test it out and report your results if you find it appropriate.
