### ISSUE TITLE
Getting 404 in link to "Essential Concepts of Linked Data" in documentation

### ISSUE THREAD

**Issue by alex-arriaga** [CarbonLDP/carbonldp-website#216]
This URL is giving me a 404: https://carbonldp.com/documents/linked-data-concepts
<img width="1075" alt="screen shot 2018-01-31 at 12 20 48 pm" src="https://user-images.githubusercontent.com/1860518/35639927-5b3d72ba-0681-11e8-9306-cbc192b24463.png">

**Comment by MiguelAraCo** [comment]
Fixed
