### ISSUE TITLE
Grammar improvements in Object Schema documentation

### ISSUE THREAD

**Issue by alex-arriaga** [CarbonLDP/carbonldp-website#219]
Here are my two cents in https://carbonldp.com/documentation/v1.0.x/javascript-sdk/reading-documents/:

1) It is better to use "number" instead of "amount" for countable nouns, like in this case.
<img width="1080" alt="amount" src="https://user-images.githubusercontent.com/1860518/35653466-6d501234-06b6-11e8-9c55-b90ab31bba0a.png">

2) I have seen, you mostly use ID instead of id (lowercase), however in this doc. the "id" in lowercase is being used:
<img width="1060" alt="id" src="https://user-images.githubusercontent.com/1860518/35653483-85c282ac-06b6-11e8-95a6-e92eae190797.png">

3) I suggest to add some commas, for a better reading in following places:
<img width="1054" alt="commas" src="https://user-images.githubusercontent.com/1860518/35653492-9be401a0-06b6-11e8-9e5a-bab9bd33c11a.png">

<img width="1078" alt="commas-2" src="https://user-images.githubusercontent.com/1860518/35653495-a0593fde-06b6-11e8-8fb0-36b5c70a7f60.png">

**Comment by codyburleson** [comment]
Closing issue. It looks like none of these issues exist for the v5 documentation and there is no longer any 1.0.x documentation for Reading Documents. Thank you for this feedback!
