### ISSUE TITLE
Create new footer

### ISSUE THREAD

**Issue by ben-bishop** [CarbonLDP/carbonldp-website#228]
<img width="723" alt="screen shot 2018-02-13 at 12 02 10 pm" src="https://user-images.githubusercontent.com/36200902/36172984-372ca1a6-10cd-11e8-8e65-a522ceaeb6a2.png">
Here is the actual design:
<img width="1449" alt="screen shot 2018-02-13 at 3 05 44 pm" src="https://user-images.githubusercontent.com/36200902/36173691-7a87b2f4-10cf-11e8-8760-ce41a88803e5.png">

Follow the layout in the attached image.

Do not include links yet for Carbon LDP, Linked Data, Privacy Policy, or ToS.

**Comment by codyburleson** [comment]
After discussion with Ben Bishop today, the footer should actually be:

Carbon LDP | Linked Data | Documentation | About | Contact Us
