### ISSUE TITLE
Create pull request to instate review of new website documentation

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#266]
Please commit documentation changes and create a pull request for me to review all new documentation so that we can get it included in the new website design. We could go into the base first, I guess and then have Mike or Alvaro move those from there into the new redesign branch, "feature/carbon-website-updates"

**Comment by mhernandeza** [comment]
Created pull request #267 - task/#182_document-rest-api

**Comment by alvaro9210** [comment]
Closing issue because the following pull requests already allow to review the documentation changes on their own thread:
- #267 - Task/#182_document-rest-api
- #225 - Feature/#209_Change documentation to new carbon constructor signatures
