### ISSUE TITLE
Create a white paper landing page

### ISSUE THREAD

**Issue by ben-bishop** [CarbonLDP/carbonldp-website#283]
Create a white paper landing page.

1. Page should contain this exact content:
<img width="1304" alt="screen shot 2018-04-06 at 12 08 30 pm" src="https://user-images.githubusercontent.com/36200902/38434232-49528e4c-3993-11e8-8141-3908cdbcead1.png">

2. The url should be: https://carbonldp.com/carbon-ldp/whitepaper

3. Add as a menu item under the Carbon LDP Level 1 menu item.

**Comment by mike-quiroga** [comment]
Does the "Download White Paper" component in the Home Page have any change?

**Comment by ben-bishop** [comment]
No change. Just want to create a page with a unique url.

Ben Bishop
Digital Marketing Manager
Base22.com     +1.901.828.3692
