### ISSUE TITLE
Add $ to SDK documentation

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-website#328]
Properties and methods for an SDK Model must begin with a `$` symbol, so users can have the liberty to use any name in the shortening of the schemas.

Simply put, if a property inside a model, begins with a `$` symbol, it means that the property or function is part of the SDK, and not of the data.

**Comment by mhernandeza** [comment]
If changes in CarbonLDP/carbonldp-js-sdk#271 are approved, the website's documentation needs to be updated accordingly.
