### ISSUE TITLE
Modify 5.0 link to license agreement

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#343]
On the following page, we will need to modify the hyperlink to the new license agreement  (if  we don't use the same page as is currently linked); if we use the same page and just  put the new license content on it, we won't have to change the link and this issue can be closed.

http://localhost:4000/documentation/v5.x.x/quick-start-guide/

**Comment by mhernandeza** [comment]
Depends on #342 being resolved before completion

**Comment by MiguelAraCo** [comment]
#342 has been merged. This issue shouldn't be blocked anymore.
