### ISSUE TITLE
Reword Premium Support and Consulting Services snippet in Community & Support page

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#345]
Reword:

_CURRENT:_

**Premium Support and Consulting Services**

While we do our best respond to all users in a timely manner, we have a limited number of support staff. As such, we are unable to make any service-level support guarantees outside of our Premium Support offering. For guaranteed response times and a direct line to our subject matter experts, please contact us by email.

services@carbonldp.com

_NEW:_

**Premium Support and Consulting Services**
					
We do our best to respond to all users in a timely manner, but we make make no service-level support guarantees for Carbon LDP Standard. Carbon LDP Enterprise customers receive the service levels specified in our Software License Agreement. For premium support, consulting services, or to obtain an Enterprise license key, please contact us by form or by email services@carbonldp.com.

(in the above new text, link "Software License Agreement" to the license agreement page, link "contact us by form" to the Contact Us (form) page, and link "services@carbonldp.com" to mailto:services@carbonldp.com.)

**Comment by mhernandeza** [comment]
Depends on #342 being resolved before completion

**Comment by MiguelAraCo** [comment]
#342 has been merged. This issue shouldn't be blocked anymore.
