### ISSUE TITLE
Remove unsupported features

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#346]
We need to remove all of the unsupported features for v5 that are published on both the Home page (https://carbonldp.com/) and on the See More Features page (https://carbonldp.com/carbon-ldp/).

On the Home page, we should have the following 3 features:

**REST API**
Access and manage applications and data by URIs using RESTful requests over HTTP (GET, POST, PUT, DELETE). Work with documents in Turtle, RDF XML, or JSON-LD. Everything in Carbon is RESTful."

**JavaScript / TypeScript SDK**
The JavaScript Software Development Kit, available from the npm package manager, allows you to manage RDF data using familiar JavaScript and TypeScript programming techniques and tools. Build for execution within a web browser or Node.js.

**RDF Native, NoSQL Graph**
Data is represented and managed as documents, but stored natively as RDF triples in a NoSQL graph database. Break the shackles of rigid data schemas; add new entities and attributes on the fly. Link data with existing resources within your apps and across the web.

On the More features page, we should have the existing snippets on:

REST API (but use the text above in this issue; it is slightly revised)
JavaScript / TypeScript SDK
Visual Tools

RDF Native, NoSQL Graph
Powerful Data Query
W3C Standards Based

Since coloration is inverted on the Home page, we may have the need for new graphics work.

**Comment by mhernandeza** [comment]
New graphics are needed for the features added to the home page so that this issue can be resolved.
