### ISSUE TITLE
Merge More Features page content into About page - leaving About page only

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#347]
Content on this page, https://carbonldp.com/carbon-ldp/, and the About page, https://carbonldp.com/about/, should be merged so that the best of all is together on just one page, which is the About page. And then the "See More Features" button on the home page should just link to the About page. Probably a peer session would be good as we do this to ensure we get the wording and all just right.

**Comment by mhernandeza** [comment]
Already merged in #363
