### ISSUE TITLE
Try Carbon Today button on Home should link to Quick Start Guide

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#368]
Home page button should link to quick start guide and we will not use the current page it goes to anymore (the register now page). 

Also on the Licensing and Pricing page, please make the hyperlinked text for Quick Start Guide in the bottom text after the pricing tables bold.

**Comment by mhernandeza** [comment]
The "Get started" page will be maintained as a call to register for Community Support and its content will be redacted.
