### ISSUE TITLE
Clicking twisty in Getting Started SDK does not expand section

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#42]
Only the text is clickable. I expected the twisty to be clickable. For a minute there, I thought the page was broken.

![clickingthetwisty](https://cloud.githubusercontent.com/assets/7317733/18810480/0a4c28be-825d-11e6-96de-1984743b861f.jpg)

**Comment by jgf20** [comment]
This issue corresponds to carbonldp-panel, as it belongs to sui customized directives in semantic/collapsible.directive.ts

Moved to CarbonLDP/carbonldp-panel#24
