### ISSUE TITLE
Should JavaScript SDK have documentation on creating Agents?

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#43]
User reported:

"For example, I tried to create a user (agent?) for my app but its not clear how to do this...do I navigate to app/agents and under "member" click "add literal"?"

We have how to do this documented in the REST API, but I do not think it is yet in the JavaScript documentation.

**Comment by MiguelAraCo** [comment]
Effort has been focused on the new version and this issue only affected the previous one. Closing.
