### ISSUE TITLE
CarbonLDP JavaScript SDK has first search result on google for keywords "carbon ldp" and no description

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#44]
![googlesearchresults](https://cloud.githubusercontent.com/assets/7317733/18810573/539475a6-825f-11e6-9fe7-d0ab17cd2166.jpg)

**Comment by jgf20** [comment]
Issue addressed in #39

**Comment by jgf20** [comment]
first search now throws correct title, but still no description.
<img width="855" alt="screen shot 2016-10-19 at 11 17 04 am" src="https://cloud.githubusercontent.com/assets/15254450/19527541/07011742-95ee-11e6-93c7-41c8a6f5ba17.png">

**Comment by jgf20** [comment]
first search now throws correct title, but still no description.
<img width="855" alt="screen shot 2016-10-19 at 11 17 04 am" src="https://cloud.githubusercontent.com/assets/15254450/19527541/07011742-95ee-11e6-93c7-41c8a6f5ba17.png">

**Comment by jgf20** [comment]
Currently investigating this issue. 
The metatags  added are not visible in the page source of prod.
<img width="612" alt="screen shot 2016-10-19 at 11 21 10 am" src="https://cloud.githubusercontent.com/assets/15254450/19527639/57edb692-95ee-11e6-817f-122e9574b015.png">

Therefore google does not see them, as shown by this fetch in google search console.
<img width="823" alt="screen shot 2016-10-19 at 11 30 02 am" src="https://cloud.githubusercontent.com/assets/15254450/19527715/b0403af4-95ee-11e6-9550-2da0c7fac5ce.png">

**Comment by jgf20** [comment]
I added the default metatgs in the index.ejs.html, now google should pick the description and add it.
This was done in branch https://github.com/CarbonLDP/carbonldp-website/tree/bug/44_metatags-not-rendering on pull request #96

**Comment by jgf20** [comment]
Since we change to static pages google is indexing our pages correctly, an authentication metatag for google search console was added to our site.

**Comment by codyburleson** [comment]
Confirmed. Looks good now; thanks.
