### ISSUE TITLE
Provide documentation for how to avoid need for login on every request

### ISSUE THREAD

**Issue by MiguelAraCo** [CarbonLDP/carbonldp-website#81]
We need documentation on the use of JSON Web Token, API key or whatever means is required for not requiring login on every single request. It seems that this is being done by the Workbench.

This comment seems to suggest the need for an API key and may be sort of a separate issue than establishing a token-based session:

"What I want is to get a token (or cookie or API key or something). I want to sprinkle Carbon on top of an existing app. So, I can't require people to login. How can I build a web metrics tool, for example, that just silently records usage data from some other app into Carbon? Or, how are you going to allow people to read your blog (if it's built on Carbon) without having to login?

**Comment by codyburleson** [comment]
Closing as resolved. See website documentation: 

**[Keeping authentication across page loads](https://carbonldp.com/documentation/javascript-sdk/authentication/#keeping-authentication-across-page-loads)**
